#%RAML 1.0
title: sw-customers-sapi-raml
baseUri: http://localhost:9092
mediaType: 
- application/json
types:
  Customer: !include datatypes/Customer.raml
  CustomerRequest: !include datatypes/CustomerRequest.raml
  UpdateCustomerRequest: !include datatypes/UpdateCustomerRequest.raml
  Address: !include datatypes/Address.raml
  AddressRequest: !include datatypes/AddressRequest.raml
  ErrorMessage: !include datatypes/ErrorMessage.raml
resourceTypes:
  collection: !include resourceTypes/collection.raml
  member: !include resourceTypes/member.raml
traits:
  pageable: !include traits/Pageable.raml
 

/customers: 
  type:
    collection
  get:
    is: [pageable]
      
    responses:
      200:
        body:
          application/json:            
            type: Customer[]
      500:
       body:
        application/json:  
          type: ErrorMessage
  post: 
    responses:
      409:
        body:
          type: ErrorMessage
          example:
            {
              "statusCode": "409",
              "message": "A Customer with same email/phone already exists"
            }
   
      
      

  /{id}:
    type:
      member
    get:  
    put:  
    